//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonusSystemConsults
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonus
    {
        public int BonusID { get; set; }
        public int ConsultID { get; set; }
        public int ChargedHours { get; set; }
        public int ChargedHoursWithBonus { get; set; }
        public int TotalHoursWithBonus { get; set; }
        public decimal BonusPot { get; set; }
        public int NetResult { get; set; }
        public Nullable<int> PeriodOfEmployment { get; set; }
        public Nullable<decimal> BonusInMoney { get; set; }
        public System.DateTime BonusDate { get; set; }
    }
}
